spring.application.name=frete_v3

# Config do mysql
spring.datasource.url=jdbc:mysql://localhost:3306/frete_v2?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Ambiente de Desenvolvimento
spring.jpa.show-sql=true


# spring.jpa.open-in-view est� ativa por padr�o, o que permite que a sess�o do JPA
# continue aberta durante a renderiza��o da view (ex: Thymeleaf, JSP).
# Isso pode causar problemas de desempenho e m� separa��o de responsabilidades,
# por isso o Spring exibe esse aviso.
spring.jpa.open-in-view=false